In [516]:
import pandas as pd
import numpy as np

ToDo:
- Add separate column to each data to indicate when this data becomes available

* testing where commits go

Data Checklist
- New car registrations
- Public holidays
- Inflation
- GDP Growth
- USD TRY

- Per Capita GDP Change - unused
- PetderAkaryakit - unused

New car Registration Data

In [517]:
df_cars = pd.read_excel("ExternalData\TUIKKaraTasıtYeniKayit.xls")

In [518]:
df_cars

,Year,Month,Akdeniz-TR6,Batı Anadolu-TR5,Batı Karadeniz-TR8,Batı Marmara-TR2,Doğu Karadeniz-TR9,Doğu Marmara-TR4,Ege-TR3,Güneydoğu Anadolu-TRC,İstanbul-TR1,Kuzeydoğu Anadolu-TRA,Orta Anadolu-TR7,Ortadoğu Anadolu-TRB
0,2013,01-Ocak,16090,13534,4292,4926,2631,10304,15519,7716,39681,1690,3969,2667
1,2013,02-Şubat,7566,6418,2049,2672,1111,4937,7820,3587,20793,834,1756,1137
2,2013,03-Mart,10920,9202,2885,3984,1524,6962,11546,4867,30890,1254,2652,1711
3,2013,04-Nisan,12895,9549,3236,4591,1684,8212,13697,5744,33105,1611,3113,1997
4,2013,05-Mayıs,16943,12884,4504,6444,2160,10850,18999,6993,48231,1948,4051,2485
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79,2019,08-Ağustos,5342,3752,1518,1978,660,3566,6639,2264,11073,445,1176,697
80,2019,09-Eylül,6959,5165,1916,2272,781,4658,7702,3116,16828,617,1551,891
81,2019,10-Ekim,8358,7137,2336,3108,1262,6404,9619,3347,22573,734,1921,1270
82,2019,11-Kasım,7853,7413,2300,2931,1408,6335,9159,3391,22390,782,1845,1319
83,2019,12-Aralık,6603,6352,2295,2780,1275,5762,8194,3209,23352,769,1786,1159

- Combine date columns

In [519]:
df_cars["Date"] = df_cars["Year"].astype(str) + "-" + df_cars['Month'].astype(str).str[0:2] + "-01"
df_cars.drop(labels=["Month","Year"],axis=1,inplace=True)

In [520]:
df_cars.head()

,Akdeniz-TR6,Batı Anadolu-TR5,Batı Karadeniz-TR8,Batı Marmara-TR2,Doğu Karadeniz-TR9,Doğu Marmara-TR4,Ege-TR3,Güneydoğu Anadolu-TRC,İstanbul-TR1,Kuzeydoğu Anadolu-TRA,Orta Anadolu-TR7,Ortadoğu Anadolu-TRB,Date
0,16090,13534,4292,4926,2631,10304,15519,7716,39681,1690,3969,2667,2013-01-01
1,7566,6418,2049,2672,1111,4937,7820,3587,20793,834,1756,1137,2013-02-01
2,10920,9202,2885,3984,1524,6962,11546,4867,30890,1254,2652,1711,2013-03-01
3,12895,9549,3236,4591,1684,8212,13697,5744,33105,1611,3113,1997,2013-04-01
4,16943,12884,4504,6444,2160,10850,18999,6993,48231,1948,4051,2485,2013-05-01

In [521]:
df_cars.columns

Index(['Akdeniz-TR6', 'Batı Anadolu-TR5', 'Batı Karadeniz-TR8',
       'Batı Marmara-TR2', 'Doğu Karadeniz-TR9', 'Doğu Marmara-TR4', 'Ege-TR3',
       'Güneydoğu Anadolu-TRC', 'İstanbul-TR1', 'Kuzeydoğu Anadolu-TRA',
       'Orta Anadolu-TR7', 'Ortadoğu Anadolu-TRB', 'Date'],
      dtype='object')

Combine into following regions
- Marmara Bölgesi    
    - TR2,TR4,TR1 
- Ege Bölgesi  
    - TR3            
- İç Anadolu Bölgesi 
    - TR5,TR7       
- Akdeniz Bölgesi
    - TR6               
- Karadeniz Bölgesi    
    - TR8,TR9        
- Güneydoğu Anadolu Bölgesi  
    - TRC   
- Doğu Anadolu Bölgesi    
    - TRA,TRB

In [522]:
# Create new columns with the sum of each region
df_cars["Marmara Bölgesi"] = df_cars[['Batı Marmara-TR2','Doğu Marmara-TR4','İstanbul-TR1']].sum(axis=1)
df_cars["Ege Bölgesi"] = df_cars['Ege-TR3']
df_cars["İç Anadolu Bölgesi"] = df_cars[['Batı Anadolu-TR5', 'Orta Anadolu-TR7']].sum(axis=1)
df_cars["Akdeniz Bölgesi"] = df_cars['Akdeniz-TR6']
df_cars["Karadeniz Bölgesi"] = df_cars[['Doğu Karadeniz-TR9','Batı Karadeniz-TR8']].sum(axis=1)
df_cars["Güneydoğu Anadolu Bölgesi"] =  df_cars['Güneydoğu Anadolu-TRC']
df_cars["Doğu Anadolu Bölgesi"] = df_cars[['Kuzeydoğu Anadolu-TRA','Ortadoğu Anadolu-TRB']].sum(axis=1)

In [523]:
# drop old columns
df_cars = df_cars[["Date","Akdeniz Bölgesi", "İç Anadolu Bölgesi","Karadeniz Bölgesi","Marmara Bölgesi", "Ege Bölgesi", "Güneydoğu Anadolu Bölgesi",
"Doğu Anadolu Bölgesi"]]

In [524]:
df_cars

,Date,Akdeniz Bölgesi,İç Anadolu Bölgesi,Karadeniz Bölgesi,Marmara Bölgesi,Ege Bölgesi,Güneydoğu Anadolu Bölgesi,Doğu Anadolu Bölgesi
0,2013-01-01,16090,17503,6923,54911,15519,7716,4357
1,2013-02-01,7566,8174,3160,28402,7820,3587,1971
2,2013-03-01,10920,11854,4409,41836,11546,4867,2965
3,2013-04-01,12895,12662,4920,45908,13697,5744,3608
4,2013-05-01,16943,16935,6664,65525,18999,6993,4433
...,...,...,...,...,...,...,...,...
79,2019-08-01,5342,4928,2178,16617,6639,2264,1142
80,2019-09-01,6959,6716,2697,23758,7702,3116,1508
81,2019-10-01,8358,9058,3598,32085,9619,3347,2004
82,2019-11-01,7853,9258,3708,31656,9159,3391,2101
83,2019-12-01,6603,8138,3570,31894,8194,3209,1928

In [525]:
# Convert to datetime object and add new column indicating when the data is available (t+2 months)
df_cars["Date"]= pd.to_datetime(df_cars['Date'])
df_cars["DataReleaseDate"] = df_cars["Date"] + pd.to_timedelta(50,unit='d')

C:\Users\feyzi\AppData\Local\Temp\ipykernel_21908\1732010456.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cars["Date"]= pd.to_datetime(df_cars['Date'])
C:\Users\feyzi\AppData\Local\Temp\ipykernel_21908\1732010456.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cars["DataReleaseDate"] = df_cars["Date"] + pd.to_timedelta(50,unit='d')

In [526]:
df_cars.head()

,Date,Akdeniz Bölgesi,İç Anadolu Bölgesi,Karadeniz Bölgesi,Marmara Bölgesi,Ege Bölgesi,Güneydoğu Anadolu Bölgesi,Doğu Anadolu Bölgesi,DataReleaseDate
0,2013-01-01,16090,17503,6923,54911,15519,7716,4357,2013-02-20
1,2013-02-01,7566,8174,3160,28402,7820,3587,1971,2013-03-23
2,2013-03-01,10920,11854,4409,41836,11546,4867,2965,2013-04-20
3,2013-04-01,12895,12662,4920,45908,13697,5744,3608,2013-05-21
4,2013-05-01,16943,16935,6664,65525,18999,6993,4433,2013-06-20

In [527]:
# Set the data release date to nearest sunday
df_cars["DataReleaseDate"] = df_cars["DataReleaseDate"] - pd.to_timedelta(df_cars["DataReleaseDate"].dt.dayofweek, unit='d') +  pd.to_timedelta(6, unit='d')

C:\Users\feyzi\AppData\Local\Temp\ipykernel_21908\3408955210.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cars["DataReleaseDate"] = df_cars["DataReleaseDate"] - pd.to_timedelta(df_cars["DataReleaseDate"].dt.dayofweek, unit='d') +  pd.to_timedelta(6, unit='d')

In [528]:
# pivot table so its easier to merge
df_cars = df_cars.melt(id_vars=["Date", "DataReleaseDate"],
var_name="Region",
value_name="Cars")

In [529]:
df_cars = df_cars[df_cars["DataReleaseDate"] > "2013-12-01" ]
df_cars.sort_values(by=["Region","Date"],inplace=True)
df_cars.reset_index(inplace=True,drop=True)

In [530]:
df_cars

          Date DataReleaseDate              Region   Cars
0   2013-11-01      2013-12-22     Akdeniz Bölgesi  12007
1   2013-12-01      2014-01-26     Akdeniz Bölgesi   9999
2   2014-01-01      2014-02-23     Akdeniz Bölgesi  15874
3   2014-02-01      2014-03-23     Akdeniz Bölgesi   6537
4   2014-03-01      2014-04-20     Akdeniz Bölgesi   8564
..         ...             ...                 ...    ...
513 2019-08-01      2019-09-22  İç Anadolu Bölgesi   4928
514 2019-09-01      2019-10-27  İç Anadolu Bölgesi   6716
515 2019-10-01      2019-11-24  İç Anadolu Bölgesi   9058
516 2019-11-01      2019-12-22  İç Anadolu Bölgesi   9258
517 2019-12-01      2020-01-26  İç Anadolu Bölgesi   8138

[518 rows x 4 columns]

- Put these into a weekly df

In [531]:
df_dates = pd.date_range('2014-01-05', '2019-12-30', freq='1W').to_frame(name='Date').reset_index(drop=True)
df_dates = pd.DataFrame(np.repeat(df_dates.values, 7, axis=0))
df_dates.columns = ["Date"]

In [532]:
df_dates["Region"] = ["Akdeniz Bölgesi", "İç Anadolu Bölgesi","Karadeniz Bölgesi","Marmara Bölgesi", "Ege Bölgesi", "Güneydoğu Anadolu Bölgesi",
"Doğu Anadolu Bölgesi"]*313

In [533]:
df_dates.sort_values(by=["Region","Date"],inplace=True)

In [534]:
df_dates.reset_index(inplace=True,drop=True)

In [535]:
df_dates["Cars"] = 0

for i in range(len(df_dates)):
    for k in range(len(df_cars)-1):
        if df_dates.loc[i,"Region"] == df_cars.loc[k,"Region"]:
            if df_dates.loc[i,"Date"] > df_cars.loc[k,"DataReleaseDate"] and df_dates.loc[i,"Date"] <= df_cars.loc[k+1,"DataReleaseDate"]:
                #print(df_dates.loc[i,"Date"], 
                #df_cars.loc[k,"DataReleaseDate"],
                #df_cars.loc[k+1,"DataReleaseDate"])
                df_dates.loc[i,"Cars"] = df_cars.loc[k,"Cars"]

In [536]:
# Add one day so it matches with the training/test data
df_dates["Date"] = df_dates["Date"] + pd.to_timedelta(1,unit='d')

In [541]:
df_dates

           Date              Region   Cars
0    2014-01-06     Akdeniz Bölgesi  12007
1    2014-01-13     Akdeniz Bölgesi  12007
2    2014-01-20     Akdeniz Bölgesi  12007
3    2014-01-27     Akdeniz Bölgesi  12007
4    2014-02-03     Akdeniz Bölgesi   9999
...         ...                 ...    ...
2186 2019-12-02  İç Anadolu Bölgesi   9058
2187 2019-12-09  İç Anadolu Bölgesi   9058
2188 2019-12-16  İç Anadolu Bölgesi   9058
2189 2019-12-23  İç Anadolu Bölgesi   9058
2190 2019-12-30  İç Anadolu Bölgesi   9258

[2191 rows x 3 columns]

In [537]:
df_dates.reset_index(inplace=True,drop=True)
df_dates.to_csv("CarRegistrationDataReady.csv",index=False)

## Public Holiday Data

In [538]:
df_holidays = pd.read_excel("ExternalData\Holidays.xlsx")

In [539]:
df_holidays

         Date           Holiday  Official  Religious  Weekend  Weekday
0  2014-01-01         New years         1          0        0        1
1  2014-04-23        23rd April         1          0        0        1
2  2014-05-01           Workers         1          0        0        1
3  2014-05-19  Youth and Sports         1          0        0        1
4  2014-07-27           Ramadan         0          1        1        0
..        ...               ...       ...        ...      ...      ...
88 2019-08-11             Candy         0          1        1        0
89 2019-08-12             Candy         0          1        0        1
90 2019-08-13             Candy         0          1        0        1
91 2019-08-14             Candy         0          1        0        1
92 2019-10-29          Republic         1          0        0        1

[93 rows x 6 columns]

In [542]:
df_holidays.drop(labels=["Holiday","Official", "Religious"],axis=1, inplace=True)

Round holiday dates to week start dates

In [543]:
df_holidays["Date"]  = df_holidays["Date"] - pd.to_timedelta(df_holidays["Date"].dt.dayofweek, unit='d')

In [544]:
df_holidays

         Date  Weekend  Weekday
0  2013-12-30        0        1
1  2014-04-21        0        1
2  2014-04-28        0        1
3  2014-05-19        0        1
4  2014-07-21        1        0
..        ...      ...      ...
88 2019-08-05        1        0
89 2019-08-12        0        1
90 2019-08-12        0        1
91 2019-08-12        0        1
92 2019-10-28        0        1

[93 rows x 3 columns]

In [545]:
# Sum up all holidays for the given week
df_holidays= df_holidays.groupby(df_holidays['Date']).aggregate("sum")

In [546]:
df_holidays.reset_index(inplace=True)
df_holidays.head()

        Date  Weekend  Weekday
0 2013-12-30        0        1
1 2014-04-21        0        1
2 2014-04-28        0        1
3 2014-05-19        0        1
4 2014-07-21        1        0

In [547]:
df_holidays.to_csv("HolidayDataReady.csv", index=False)

### Inflation data

In [548]:
df_inflation = pd.read_excel("ExternalData\Inflation.xls")

In [549]:
df_inflation

    Year       Month  MoMInflation%
0   2013     01-Ocak           1.65
1   2013    02-Şubat           0.30
2   2013     03-Mart           0.66
3   2013    04-Nisan           0.42
4   2013    05-Mayıs           0.15
..   ...         ...            ...
79  2019  08-Ağustos           0.86
80  2019    09-Eylül           0.99
81  2019     10-Ekim           2.00
82  2019    11-Kasım           0.38
83  2019   12-Aralık           0.74

[84 rows x 3 columns]

In [550]:
df_inflation["Date"] = df_inflation["Year"].astype(str) + "-" + df_inflation['Month'].astype(str).str[0:2] + "-01"
df_inflation.drop(labels=["Month","Year"],axis=1,inplace=True)

In [551]:
# Convert to datetime object and add new column indicating when the data is available (t+1 months)
df_inflation["Date"]= pd.to_datetime(df_inflation['Date'])
df_inflation["DataReleaseDate"] = df_inflation["Date"] + pd.to_timedelta(32,unit='d')

In [552]:
# Set the data release date to nearest sunday
df_inflation["DataReleaseDate"] = df_inflation["DataReleaseDate"] - pd.to_timedelta(df_inflation["DataReleaseDate"].dt.dayofweek, unit='d') +  pd.to_timedelta(6, unit='d')

In [553]:
df_inflation

    MoMInflation%       Date DataReleaseDate
0            1.65 2013-01-01      2013-02-03
1            0.30 2013-02-01      2013-03-10
2            0.66 2013-03-01      2013-04-07
3            0.42 2013-04-01      2013-05-05
4            0.15 2013-05-01      2013-06-02
..            ...        ...             ...
79           0.86 2019-08-01      2019-09-08
80           0.99 2019-09-01      2019-10-06
81           2.00 2019-10-01      2019-11-03
82           0.38 2019-11-01      2019-12-08
83           0.74 2019-12-01      2020-01-05

[84 rows x 3 columns]

- Put these into a weekly df

In [554]:
df_dates = pd.date_range('2014-01-05', '2019-12-30', freq='1W').to_frame(name='Date').reset_index(drop=True)
df_dates.columns = ["Date"]
df_dates.sort_values(by="Date",inplace=True)
df_dates.reset_index(inplace=True,drop=True)

In [555]:
df_dates["MoMInflation%"] = 0

for i in range(len(df_dates)):
    for k in range(len(df_inflation)-1):
        if df_dates.loc[i,"Date"] > df_inflation.loc[k,"DataReleaseDate"] and df_dates.loc[i,"Date"] <= df_inflation.loc[k+1,"DataReleaseDate"]:
            df_dates.loc[i,"MoMInflation%"] = df_inflation.loc[k,"MoMInflation%"]

In [556]:
# Add one day so it matches with the training/test data
df_dates["Date"] = df_dates["Date"] + pd.to_timedelta(1,unit='d')

In [557]:
df_dates.head()

        Date  MoMInflation%
0 2014-01-06           0.01
1 2014-01-13           0.46
2 2014-01-20           0.46
3 2014-01-27           0.46
4 2014-02-03           0.46

In [558]:
df_dates.reset_index(inplace=True,drop=True)
df_dates.to_csv("InflationDataReady.csv",index=False)

# GDP Growth Data

In [559]:
df_gdp = pd.read_excel("ExternalData\GDPGrowth.xlsx")
df_gdp.columns = ["DataReleaseDate", "GDPGrowth%"]

In [560]:
df_gdp.head()

  DataReleaseDate  GDPGrowth%
0    Dec 02, 2019       0.009
1    Sep 02, 2019      -0.015
2    May 31, 2019      -0.026
3    Mar 11, 2019      -0.030
4    Dec 10, 2018       0.016

In [561]:
df_gdp["DataReleaseDate"] = pd.to_datetime(df_gdp['DataReleaseDate'])

In [562]:
df_gdp.sort_values(by="DataReleaseDate",inplace=True)
df_gdp.reset_index(inplace=True,drop=True)
df_gdp.head(-1)

   DataReleaseDate  GDPGrowth%
0       2013-12-10       0.044
1       2014-03-31       0.044
2       2014-06-10       0.043
3       2014-09-10       0.021
4       2014-12-10       0.017
5       2015-03-31       0.026
6       2015-06-10       0.023
7       2015-09-10       0.038
8       2015-12-10       0.040
9       2016-03-31       0.057
10      2016-06-10       0.048
11      2016-09-09       0.031
12      2016-12-12      -0.018
13      2017-03-31       0.035
14      2017-06-12       0.050
15      2017-09-11       0.051
16      2017-12-11       0.111
17      2018-03-29       0.073
18      2018-06-11       0.074
19      2018-09-10       0.052
20      2018-12-10       0.016
21      2019-03-11      -0.030
22      2019-05-31      -0.026
23      2019-09-02      -0.015

- Put these into a weekly df

In [563]:
df_dates = pd.date_range('2014-01-05', '2019-12-30', freq='1W').to_frame(name='Date').reset_index(drop=True)
df_dates.columns = ["Date"]
df_dates.sort_values(by="Date",inplace=True)
df_dates.reset_index(inplace=True,drop=True)

In [564]:
df_dates["GDPGrowth%"] = 0

for i in range(len(df_dates)):
    for k in range(len(df_gdp)-1):
        if df_dates.loc[i,"Date"] > df_gdp.loc[k,"DataReleaseDate"] and df_dates.loc[i,"Date"] <= df_gdp.loc[k+1,"DataReleaseDate"]:
            df_dates.loc[i,"GDPGrowth%"] = df_gdp.loc[k,"GDPGrowth%"]

    # set last 4 entries manually
    if i >= 309:
        df_dates.loc[i,"GDPGrowth%"] = df_gdp.loc[len(df_gdp)-1,"GDPGrowth%"]

In [566]:
# Add one day so it matches with the training/test data
df_dates["Date"] = df_dates["Date"] + pd.to_timedelta(1,unit='d')
df_dates

          Date  GDPGrowth%
0   2014-01-06       0.044
1   2014-01-13       0.044
2   2014-01-20       0.044
3   2014-01-27       0.044
4   2014-02-03       0.044
..         ...         ...
308 2019-12-02      -0.015
309 2019-12-09       0.009
310 2019-12-16       0.009
311 2019-12-23       0.009
312 2019-12-30       0.009

[313 rows x 2 columns]

In [567]:
df_dates.reset_index(inplace=True,drop=True)
df_dates.to_csv("GDPDataReady.csv",index=False)

# USD TRY DATA

In [568]:
df_usd = pd.read_csv(r"ExternalData\USDTRYWeeklyChanges.csv")

In [569]:
df_usd["Date"] = pd.to_datetime(df_usd['Date'])

C:\Users\feyzi\AppData\Local\Temp\ipykernel_21908\2725949409.py:1: UserWarning: Parsing '29.12.2019' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  df_usd["Date"] = pd.to_datetime(df_usd['Date'])
C:\Users\feyzi\AppData\Local\Temp\ipykernel_21908\2725949409.py:1: UserWarning: Parsing '22.12.2019' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  df_usd["Date"] = pd.to_datetime(df_usd['Date'])
C:\Users\feyzi\AppData\Local\Temp\ipykernel_21908\2725949409.py:1: UserWarning: Parsing '15.12.2019' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  df_usd["Date"] = pd.to_datetime(df_usd['Date'])
C:\Users\feyzi\AppData\Local\Temp\ipykernel_21908\2725949409.py:1: UserWarning: Parsing '24.11.2019' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  df_usd["Date"] = pd.to_datetime(df_usd['Date'])
C:\Users\feyzi\AppData\Local\Temp\ipykernel_21908\2725949409.py:1: UserWarning: Parsing '17.11.2019' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  df_usd["Date"] = pd.to_datetime(df_usd['Date'])
C:\Users\feyzi\AppData\Local\Temp\ipykernel_21908\2725949409.py:1: UserWarning: Parsing '27.10.2019' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  df_usd["Date"] = pd.to_datetime(df_usd['Date'])
C:\Users\feyzi\AppData\Local\Temp\ipykernel_21908\2725949409.py:1: UserWarning: Parsing '20.10.2019' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  df_usd["Date"] = pd.to_datetime(df_usd['Date'])
C:\Users\feyzi\AppData\Local\Temp\ipykernel_21908\2725949409.py:1: UserWarning: Parsing '13.10.2019' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  df_usd["Date"] = pd.to_datetime(df_usd['Date'])
C:\Users\feyzi\AppData\Local\Temp\ipykernel_21908\2725949409.py:1: UserWarning: Parsing '29.09.2019' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  df_usd["Date"] = pd.to_datetime(df_usd['Date'])
C:\Users\feyzi\AppData\Local\Temp\ipykernel_21908\2725949409.py:1: UserWarning: Parsing '22.09.2019' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  df_usd["Date"] = pd.to_datetime(df_usd['Date'])
C:\Users\feyzi\AppData\Local\Temp\ipykernel_21908\2725949409.py:1: UserWarning: Parsing '15.09.2019' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  df_usd["Date"] = pd.to_datetime(df_usd['Date'])
C:\Users\feyzi\AppData\Local\Temp\ipykernel_21908\2725949409.py:1: UserWarning: Parsing '25.08.2019' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  df_usd["Date"] = pd.to_datetime(df_usd['Date'])
C:\Users\feyzi\AppData\Local\Temp\ipykernel_21908\2725949409.py:1: UserWarning: Parsing '18.08.2019' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  df_usd["Date"] = pd.to_datetime(df_usd['Date'])
C:\Users\feyzi\AppData\Local\Temp\ipykernel_21908\2725949409.py:1: UserWarning: Parsing '28.07.2019' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  df_usd["Date"] = pd.to_datetime(df_usd['Date'])
C:\Users\feyzi\AppData\Local\Temp\ipykernel_21908\2725949409.py:1: UserWarning: Parsing '21.07.2019' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  df_usd["Date"] = pd.to_datetime(df_usd['Date'])
C:\Users\feyzi\AppData\Local\Temp\ipykernel_21908\2725949409.py:1: UserWarning: Parsing '14.07.2019' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  df_usd["Date"] = pd.to_datetime(df_usd['Date'])
C:\Users\feyzi\AppData\Local\Temp\ipykernel_21908\2725949409.py:1: UserWarning: Parsing '30.06.2019' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  df_usd["Date"] = pd.to_datetime(df_usd['Date'])
C:\Users\feyzi\AppData\Local\Temp\ipykernel_21908\2725949409.py:1: UserWarning: Parsing '23.06.2019' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  df_usd["Date"] = pd.to_datetime(df_usd['Date'])
C:\Users\feyzi\AppData\Local\Temp\ipykernel_21908\2725949409.py:1: UserWarning: Parsing '16.06.2019' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  df_usd["Date"] = pd.to_datetime(df_usd['Date'])
C:\Users\feyzi\AppData\Local\Temp\ipykernel_21908\2725949409.py:1: UserWarning: Parsing '26.05.2019' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  df_usd["Date"] = pd.to_datetime(df_usd['Date'])
C:\Users\feyzi\AppData\Local\Temp\ipykernel_21908\2725949409.py:1: UserWarning: Parsing '19.05.2019' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  df_usd["Date"] = pd.to_datetime(df_usd['Date'])
C:\Users\feyzi\AppData\Local\Temp\ipykernel_21908\2725949409.py:1: UserWarning: Parsing '28.04.2019' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  df_usd["Date"] = pd.to_datetime(df_usd['Date'])
C:\Users\feyzi\AppData\Local\Temp\ipykernel_21908\2725949409.py:1: UserWarning: Parsing '21.04.2019' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  df_usd["Date"] = pd.to_datetime(df_usd['Date'])
C:\Users\feyzi\AppData\Local\Temp\ipykernel_21908\2725949409.py:1: UserWarning: Parsing '14.04.2019' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  df_usd["Date"] = pd.to_datetime(df_usd['Date'])
C:\Users\feyzi\AppData\Local\Temp\ipykernel_21908\2725949409.py:1: UserWarning: Parsing '31.03.2019' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  df_usd["Date"] = pd.to_datetime(df_usd['Date'])
C:\Users\feyzi\AppData\Local\Temp\ipykernel_21908\2725949409.py:1: UserWarning: Parsing '24.03.2019' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  df_usd["Date"] = pd.to_datetime(df_usd['Date'])
C:\Users\feyzi\AppData\Local\Temp\ipykernel_21908\2725949409.py:1: UserWarning: Parsing '17.03.2019' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  df_usd["Date"] = pd.to_datetime(df_usd['Date'])
C:\Users\feyzi\AppData\Local\Temp\ipykernel_21908\2725949409.py:1: UserWarning: Parsing '24.02.2019' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  df_usd["Date"] = pd.to_datetime(df_usd['Date'])
C:\Users\feyzi\AppData\Local\Temp\ipykernel_21908\2725949409.py:1: UserWarning: Parsing '17.02.2019' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  df_usd["Date"] = pd.to_datetime(df_usd['Date'])
C:\Users\feyzi\AppData\Local\Temp\ipykernel_21908\2725949409.py:1: UserWarning: Parsing '27.01.2019' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  df_usd["Date"] = pd.to_datetime(df_usd['Date'])
C:\Users\feyzi\AppData\Local\Temp\ipykernel_21908\2725949409.py:1: UserWarning: Parsing '20.01.2019' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  df_usd["Date"] = pd.to_datetime(df_usd['Date'])
C:\Users\feyzi\AppData\Local\Temp\ipykernel_21908\2725949409.py:1: UserWarning: Parsing '13.01.2019' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  df_usd["Date"] = pd.to_datetime(df_usd['Date'])
C:\Users\feyzi\AppData\Local\Temp\ipykernel_21908\2725949409.py:1: UserWarning: Parsing '30.12.2018' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  df_usd["Date"] = pd.to_datetime(df_usd['Date'])
C:\Users\feyzi\AppData\Local\Temp\ipykernel_21908\2725949409.py:1: UserWarning: Parsing '23.12.2018' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  df_usd["Date"] = pd.to_datetime(df_usd['Date'])
C:\Users\feyzi\AppData\Local\Temp\ipykernel_21908\2725949409.py:1: UserWarning: Parsing '16.12.2018' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  df_usd["Date"] = pd.to_datetime(df_usd['Date'])
C:\Users\feyzi\AppData\Local\Temp\ipykernel_21908\2725949409.py:1: UserWarning: Parsing '25.11.2018' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  df_usd["Date"] = pd.to_datetime(df_usd['Date'])
C:\Users\feyzi\AppData\Local\Temp\ipykernel_21908\2725949409.py:1: UserWarning: Parsing '18.11.2018' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  df_usd["Date"] = pd.to_datetime(df_usd['Date'])
C:\Users\feyzi\AppData\Local\Temp\ipykernel_21908\2725949409.py:1: UserWarning: Parsing '28.10.2018' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  df_usd["Date"] = pd.to_datetime(df_usd['Date'])
C:\Users\feyzi\AppData\Local\Temp\ipykernel_21908\2725949409.py:1: UserWarning: Parsing '21.10.2018' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  df_usd["Date"] = pd.to_datetime(df_usd['Date'])
C:\Users\feyzi\AppData\Local\Temp\ipykernel_21908\2725949409.py:1: UserWarning: Parsing '14.10.2018' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  df_usd["Date"] = pd.to_datetime(df_usd['Date'])
C:\Users\feyzi\AppData\Local\Temp\ipykernel_21908\2725949409.py:1: UserWarning: Parsing '30.09.2018' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  df_usd["Date"] = pd.to_datetime(df_usd['Date'])
C:\Users\feyzi\AppData\Local\Temp\ipykernel_21908\2725949409.py:1: UserWarning: Parsing '23.09.2018' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  df_usd["Date"] = pd.to_datetime(df_usd['Date'])
C:\Users\feyzi\AppData\Local\Temp\ipykernel_21908\2725949409.py:1: UserWarning: Parsing '16.09.2018' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  df_usd["Date"] = pd.to_datetime(df_usd['Date'])
C:\Users\feyzi\AppData\Local\Temp\ipykernel_21908\2725949409.py:1: UserWarning: Parsing '26.08.2018' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  df_usd["Date"] = pd.to_datetime(df_usd['Date'])
C:\Users\feyzi\AppData\Local\Temp\ipykernel_21908\2725949409.py:1: UserWarning: Parsing '19.08.2018' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  df_usd["Date"] = pd.to_datetime(df_usd['Date'])
C:\Users\feyzi\AppData\Local\Temp\ipykernel_21908\2725949409.py:1: UserWarning: Parsing '29.07.2018' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  df_usd["Date"] = pd.to_datetime(df_usd['Date'])
C:\Users\feyzi\AppData\Local\Temp\ipykernel_21908\2725949409.py:1: UserWarning: Parsing '22.07.2018' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  df_usd["Date"] = pd.to_datetime(df_usd['Date'])
C:\Users\feyzi\AppData\Local\Temp\ipykernel_21908\2725949409.py:1: UserWarning: Parsing '15.07.2018' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  df_usd["Date"] = pd.to_datetime(df_usd['Date'])
C:\Users\feyzi\AppData\Local\Temp\ipykernel_21908\2725949409.py:1: UserWarning: Parsing '24.06.2018' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  df_usd["Date"] = pd.to_datetime(df_usd['Date'])
C:\Users\feyzi\AppData\Local\Temp\ipykernel_21908\2725949409.py:1: UserWarning: Parsing '17.06.2018' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  df_usd["Date"] = pd.to_datetime(df_usd['Date'])
C:\Users\feyzi\AppData\Local\Temp\ipykernel_21908\2725949409.py:1: UserWarning: Parsing '27.05.2018' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  df_usd["Date"] = pd.to_datetime(df_usd['Date'])
C:\Users\feyzi\AppData\Local\Temp\ipykernel_21908\2725949409.py:1: UserWarning: Parsing '20.05.2018' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  df_usd["Date"] = pd.to_datetime(df_usd['Date'])
C:\Users\feyzi\AppData\Local\Temp\ipykernel_21908\2725949409.py:1: UserWarning: Parsing '13.05.2018' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  df_usd["Date"] = pd.to_datetime(df_usd['Date'])
C:\Users\feyzi\AppData\Local\Temp\ipykernel_21908\2725949409.py:1: UserWarning: Parsing '29.04.2018' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  df_usd["Date"] = pd.to_datetime(df_usd['Date'])
C:\Users\feyzi\AppData\Local\Temp\ipykernel_21908\2725949409.py:1: UserWarning: Parsing '22.04.2018' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  df_usd["Date"] = pd.to_datetime(df_usd['Date'])
C:\Users\feyzi\AppData\Local\Temp\ipykernel_21908\2725949409.py:1: UserWarning: Parsing '15.04.2018' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  df_usd["Date"] = pd.to_datetime(df_usd['Date'])
C:\Users\feyzi\AppData\Local\Temp\ipykernel_21908\2725949409.py:1: UserWarning: Parsing '25.03.2018' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  df_usd["Date"] = pd.to_datetime(df_usd['Date'])
C:\Users\feyzi\AppData\Local\Temp\ipykernel_21908\2725949409.py:1: UserWarning: Parsing '18.03.2018' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  df_usd["Date"] = pd.to_datetime(df_usd['Date'])
C:\Users\feyzi\AppData\Local\Temp\ipykernel_21908\2725949409.py:1: UserWarning: Parsing '25.02.2018' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  df_usd["Date"] = pd.to_datetime(df_usd['Date'])
C:\Users\feyzi\AppData\Local\Temp\ipykernel_21908\2725949409.py:1: UserWarning: Parsing '18.02.2018' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  df_usd["Date"] = pd.to_datetime(df_usd['Date'])
C:\Users\feyzi\AppData\Local\Temp\ipykernel_21908\2725949409.py:1: UserWarning: Parsing '28.01.2018' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  df_usd["Date"] = pd.to_datetime(df_usd['Date'])
C:\Users\feyzi\AppData\Local\Temp\ipykernel_21908\2725949409.py:1: UserWarning: Parsing '21.01.2018' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  df_usd["Date"] = pd.to_datetime(df_usd['Date'])
C:\Users\feyzi\AppData\Local\Temp\ipykernel_21908\2725949409.py:1: UserWarning: Parsing '14.01.2018' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  df_usd["Date"] = pd.to_datetime(df_usd['Date'])
C:\Users\feyzi\AppData\Local\Temp\ipykernel_21908\2725949409.py:1: UserWarning: Parsing '31.12.2017' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  df_usd["Date"] = pd.to_datetime(df_usd['Date'])
C:\Users\feyzi\AppData\Local\Temp\ipykernel_21908\2725949409.py:1: UserWarning: Parsing '24.12.2017' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  df_usd["Date"] = pd.to_datetime(df_usd['Date'])
C:\Users\feyzi\AppData\Local\Temp\ipykernel_21908\2725949409.py:1: UserWarning: Parsing '17.12.2017' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  df_usd["Date"] = pd.to_datetime(df_usd['Date'])
C:\Users\feyzi\AppData\Local\Temp\ipykernel_21908\2725949409.py:1: UserWarning: Parsing '26.11.2017' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  df_usd["Date"] = pd.to_datetime(df_usd['Date'])
C:\Users\feyzi\AppData\Local\Temp\ipykernel_21908\2725949409.py:1: UserWarning: Parsing '19.11.2017' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  df_usd["Date"] = pd.to_datetime(df_usd['Date'])
C:\Users\feyzi\AppData\Local\Temp\ipykernel_21908\2725949409.py:1: UserWarning: Parsing '29.10.2017' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  df_usd["Date"] = pd.to_datetime(df_usd['Date'])
C:\Users\feyzi\AppData\Local\Temp\ipykernel_21908\2725949409.py:1: UserWarning: Parsing '22.10.2017' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  df_usd["Date"] = pd.to_datetime(df_usd['Date'])
C:\Users\feyzi\AppData\Local\Temp\ipykernel_21908\2725949409.py:1: UserWarning: Parsing '15.10.2017' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  df_usd["Date"] = pd.to_datetime(df_usd['Date'])
C:\Users\feyzi\AppData\Local\Temp\ipykernel_21908\2725949409.py:1: UserWarning: Parsing '24.09.2017' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  df_usd["Date"] = pd.to_datetime(df_usd['Date'])
C:\Users\feyzi\AppData\Local\Temp\ipykernel_21908\2725949409.py:1: UserWarning: Parsing '17.09.2017' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  df_usd["Date"] = pd.to_datetime(df_usd['Date'])
C:\Users\feyzi\AppData\Local\Temp\ipykernel_21908\2725949409.py:1: UserWarning: Parsing '27.08.2017' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  df_usd["Date"] = pd.to_datetime(df_usd['Date'])
C:\Users\feyzi\AppData\Local\Temp\ipykernel_21908\2725949409.py:1: UserWarning: Parsing '20.08.2017' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  df_usd["Date"] = pd.to_datetime(df_usd['Date'])
C:\Users\feyzi\AppData\Local\Temp\ipykernel_21908\2725949409.py:1: UserWarning: Parsing '13.08.2017' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  df_usd["Date"] = pd.to_datetime(df_usd['Date'])
C:\Users\feyzi\AppData\Local\Temp\ipykernel_21908\2725949409.py:1: UserWarning: Parsing '30.07.2017' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  df_usd["Date"] = pd.to_datetime(df_usd['Date'])
C:\Users\feyzi\AppData\Local\Temp\ipykernel_21908\2725949409.py:1: UserWarning: Parsing '23.07.2017' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  df_usd["Date"] = pd.to_datetime(df_usd['Date'])
C:\Users\feyzi\AppData\Local\Temp\ipykernel_21908\2725949409.py:1: UserWarning: Parsing '16.07.2017' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  df_usd["Date"] = pd.to_datetime(df_usd['Date'])
C:\Users\feyzi\AppData\Local\Temp\ipykernel_21908\2725949409.py:1: UserWarning: Parsing '25.06.2017' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  df_usd["Date"] = pd.to_datetime(df_usd['Date'])

In [570]:
df_usd.sort_values(by="Date",inplace=True)
df_usd.reset_index(inplace=True,drop=True)

In [571]:
df_usd

          Date WoWChange%
0   2014-01-06     -0,91%
1   2014-01-26     -3,04%
2   2014-02-02     -1,80%
3   2014-02-03     -0,17%
4   2014-02-11      1,53%
..         ...        ...
305 2019-11-24      0,59%
306 2019-12-05      1,31%
307 2019-12-15      2,21%
308 2019-12-22      0,23%
309 2019-12-29      0,37%

[310 rows x 2 columns]

In [572]:
df_usd.to_csv("USDDataReady.csv",index=False)